# write me
language: python

dist: trusty
sudo: required

env:
  global:
    - ROUTEROS_VERSION=6.43.4
  # matrix:
  #   - USE_NETWORK=true
  #   - USE_NETWORK=false

matrix:
  allow_failures:
    - os: osx
      python: 2.7
    - os: osx
      python: 3.3
    - os: linux
      python: 3.3
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: osx
      python: 2.7
    - os: osx
      python: 3.3

before_install:
  - test/travis.install.sh

install: 
  - pip install -r requirements.txt

before_script:
  - test/run_server.sh

script:
  - ansible-playbook -i inventory routeros.yml --tags install -vvv
  - ansible-playbook -i inventory.secure routeros.yml --tags shutdown -vvv

after_script:
  - killall qemu-system-x86_64