# write me
language: python

dist: trusty
sudo: required

env:
  global:
    - ROUTEROS_VERSION=6.43.4
  # matrix:
  #   - USE_NETWORK=true
  #   - USE_NETWORK=false

matrix:
  allow_failures:
    - os: osx
      python: 2.7
    - os: osx
      python: 3.3
    - os: linux
      python: 3.3
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: osx
      python: 2.7
    - os: osx
      python: 3.3

before_install:
  - test/travis.install.sh

install: 
  - pip install -r test/requirements.txt

before_script:
  - test/run_server.sh

script:
  # Check the role/playbook's syntax.
  # - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i test/inventory test/routeros.yml --syntax-check
  # install
  - ANSIBLE_CONFIG=test/ansible.cfg ansible-playbook -i test/inventory test/routeros.yml --tags install -vvvv
  # shutdown 
  - ANSIBLE_CONFIG=test/ansible.cfg ansible-playbook -i test/inventory.secure test/routeros.yml --tags shutdown -vvvv
  # lint
  - ansible-lint test/routeros.yml || true

after_script:
  - killall qemu-system-x86_64 && false